language: elixir
cache:
  directories:
    - _build
    - deps
services:
  - docker
  - postgresql
addons:
  postgresql: "9.6"
elixir:
  - 1.4.2
otp_release:
  - 19.2
env:
  global:
    - MIX_ENV=test
    - DOCKER_HUB_ACCOUNT=nebo15
    - MAIN_BRANCHES="master" # Branches on which you want version to be incremented
    - RELEASE_BRANCH="master"
    - secure: "ayklvzkuBh9pv9GvSFYp306oRWp/V+9f2LNGYSweLkRWdc0MxXDPIrV+zZLDKI/Yi4zHJl94eafGuGDz2xnk4rQGcEREcW4tmBAmXvsNCcnT9/z6oAfRifkda4ZFB4IZ9Azq5oAhJ9s/3ZJc9eFUYoy+fWbZerJcoiO9r75MnklRAUxPE0vJyplUU2Sza01N77QKiySA7MB2MbIKQbSZ3otqGjEtREkMJjZmGgMboS9cBlakoUZ2jv2beSFOEyEDLhwlJs/DgarUKajkeEVXQ72WnOXbsUeFFHeScn1imEsdLX2cRbNZk14KoAQx7TiZdsyrCtm3HDECBrN8vD8Wje/QfNPmsd5XjIV89SnGY3EdPAaVa0lK0Xb5oTbA9f0SaxaPBbQJDanc9g7DFTg42jCDnlzzWsVByVE7qkkTCkS6JEX1L8Dd+84fsqWWt3owM9BU8+7aAfgPf/XrCqkXq146JJ0D7yyFfJiy1B1vafjunQAk1p65Hy+3qmcCOuUnCPX5qVBP6xiJkrkMuaKKbsrwrd0nTMuuTyyGAJciGwM1x9VgyQA47UYbmAYqPRom90T2YTNMYYUbmSzWYZBfpgxhOR7cF4zukrVGXHTbsffAvCY7GPPoBVNbZbKem8yUXo1hNIw2S2rnJ37b3fq1SVPqXkoRklQ0UyuIlaI65Kc="
    - secure: "j/ScSq5CybsQM2bx0duVEhryAh3iB8mEe/9dB4ZMxO8+fsPNVHetP0kqibYbml2vqKIviTktJBCi57oEHhFvhfOa/e6nehcXT6t+zdNdc4gIgs1QQ2HQ1E1YsVET8s9hxn+CT8PdDAvZ9PLwUozdnZRJHxTPtTS/BFa0WTlNEuJl8byGIGPuPlyv7NfI57jkyLPzCw0vuA8JmwZyHkvR8pDanMLPwg6L4IqulkDuJPZ/nykb+Zeb7OSOhWsC5GorSSn5wExf4XP0t1lENzKJJMYhX41+vYPPNu12nfqVb5AVnmpapuQNeOkGSkGj87LQ1qkrgxzxM8NiFWcDB7UTcq9xSmmLI3T9rhEJgeVYQbbA7vX983agEefYnxa59dNOEMuq3FHwlV9EhM7wXICATmI6DEFJflu9bu1a+QfbYvAz+OaDYx6LiZTNraiVQfPXKxpr6VFehPX6K0N3Vu0T373tjf8Iq4wqMj/YI5JLCDQTSPOLZ0tYm6ZL+PjzTd/iCC/PXvQ6tP5wrNMi7DQQJrqws3Pk5WbeQRitGyAGVyv7V2TBoazaC/0oSKQho/zv3dtryR0EfFLATNBzaZJtoxWLudbb+qD9FuEAuRiBpQigO8FhLlFtLdoW6Nau4CF6M+A+Zub41ES8DUfSy9etspRODoQz+F8V2utFOSc04bg="
branches:
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  # Expose DB to Docker container
  - ./bin/ci/init-db.sh
script:
  # Increment version in mix.exs
  - ./bin/ci/version-increment.sh
  # Run all tests except pending ones
  - mix test --exclude pending --trace
  # Submit code coverage report to Coveralls
  # Add --pro if you using private repo.
  - mix coveralls.travis --exclude pending
  # Run static code analysis
  - mix credo --strict
  # Check code style
  - mix dogma
  # Build Docker container
  - ./bin/build.sh
  # Initialize DB for Docker container
  - MIX_ENV=dev mix ecto.setup
  # Run Docker container
  - ./bin/start.sh
  - sleep 5
  - docker ps
  - RUNNING_CONTAINERS=`docker ps | wc -l`;
  - if [ "${RUNNING_CONTAINERS//[[:space:]]/}" == "1" ]; then echo "[E] Container is not started\!"; docker logs ehealth --details --since 5h; exit 1; fi;
after_failure:
  - docker logs ehealth --details --since 5h
after_success:
  # Submit Docker container to Docker Hub and create GitHub Release by pushing tag with changelog
  - ./bin/ci/push.sh
